package ngrok

import (
	"fmt"
	"net/url"
)

// Errors arising from authentication failure.
type ErrAuthFailed struct {
	// Whether the error was generated by the remote server, or in the sending
	// of the authentication request.
	Remote bool
	// The underlying error.
	Inner error
}

func (e ErrAuthFailed) Error() string {
	var msg string
	if e.Remote {
		msg = "authentication failed"
	} else {
		msg = "failed to send authentication request"
	}

	return fmt.Sprintf("%s: %v", msg, e.Inner)
}

func (e ErrAuthFailed) Unwrap() error {
	return e.Inner
}

func (e ErrAuthFailed) Is(target error) bool {
	_, ok := target.(ErrAuthFailed)
	return ok
}

// The error returned by [Tunnel]'s [net.Listener.Accept] method.
type ErrAcceptFailed struct {
	// The underlying error.
	Inner error
}

func (e ErrAcceptFailed) Error() string {
	return fmt.Sprintf("failed to accept connection: %v", e.Inner)
}

func (e ErrAcceptFailed) Unwrap() error {
	return e.Inner
}

func (e ErrAcceptFailed) Is(target error) bool {
	_, ok := target.(ErrAcceptFailed)
	return ok
}

// Errors arising from a failure to start a tunnel.
type ErrStartTunnel struct {
	// The underlying error.
	Inner error
}

func (e ErrStartTunnel) Error() string {
	return fmt.Sprintf("failed to start tunnel: %v", e.Inner)
}

func (e ErrStartTunnel) Unwrap() error {
	return e.Inner
}

func (e ErrStartTunnel) Is(target error) bool {
	_, ok := target.(ErrStartTunnel)
	return ok
}

// Errors arising from a failure to construct a [golang.org/x/net/proxy.Dialer] from a [url.URL].
type ErrProxyInit struct {
	// The provided proxy URL.
	URL *url.URL
	// The underlying error.
	Inner error
}

func (e ErrProxyInit) Error() string {
	return fmt.Sprintf("failed to construct proxy dialer from \"%s\": %v", e.URL.String(), e.Inner)
}

func (e ErrProxyInit) Unwrap() error {
	return e.Inner
}

func (e ErrProxyInit) Is(target error) bool {
	_, ok := target.(ErrProxyInit)
	return ok
}

// Error arising from a failure to dial the ngrok server.
type ErrSessionDial struct {
	// The address to which a connection was attempted.
	Addr string
	// The underlying error.
	Inner error
}

func (e ErrSessionDial) Error() string {
	return fmt.Sprintf("failed to dial ngrok server with address \"%s\": %v", e.Addr, e.Inner)
}

func (e ErrSessionDial) Unwrap() error {
	return e.Inner
}

func (e ErrSessionDial) Is(target error) bool {
	_, ok := target.(ErrSessionDial)
	return ok
}
