// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lib/private_dial/private_dial.proto

package pb_private_dial

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionReq is the first message the client sends on the /session
// request body. Auth is carried in the HTTP Authorization header, not in
// this message; SessionReq carries client identity and free-form
// metadata for server-side logging.
type SessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReq) Reset() {
	*x = SessionReq{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReq) ProtoMessage() {}

func (x *SessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReq.ProtoReflect.Descriptor instead.
func (*SessionReq) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{0}
}

func (x *SessionReq) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *SessionReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SessionAck is the first message the server sends on the control stream
// response body after successful auth. Subsequent frames on the control
// stream are ControlFrame messages.
type SessionAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id identifies the server instance that terminated this
	// session. Useful for client-side logging and request correlation.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// ping_interval is the cadence at which the server expects to send
	// and receive Ping frames on the control stream. Clients should
	// observe this for their own ping cadence.
	PingInterval  *durationpb.Duration `protobuf:"bytes,2,opt,name=ping_interval,json=pingInterval,proto3" json:"ping_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAck) Reset() {
	*x = SessionAck{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAck) ProtoMessage() {}

func (x *SessionAck) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAck.ProtoReflect.Descriptor instead.
func (*SessionAck) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{1}
}

func (x *SessionAck) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SessionAck) GetPingInterval() *durationpb.Duration {
	if x != nil {
		return x.PingInterval
	}
	return nil
}

// Ping is sent by either side to measure RTT and prove liveness. The
// peer must immediately reply with a Pong carrying the same token.
// Token is opaque correlation data — typically 8 random bytes,
// mirroring HTTP/2 PING semantics.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         uint64                 `protobuf:"fixed64,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

// Pong echoes the token from a received Ping.
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         uint64                 `protobuf:"fixed64,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

// PleaseDrain tells the client that the server is draining. The client should
// stop opening new dial streams on this session and allow existing streams to
// finish within grace_period_seconds. Server-to-client only.
type PleaseDrain struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Reason             string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	GracePeriodSeconds uint32                 `protobuf:"varint,2,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PleaseDrain) Reset() {
	*x = PleaseDrain{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PleaseDrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PleaseDrain) ProtoMessage() {}

func (x *PleaseDrain) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PleaseDrain.ProtoReflect.Descriptor instead.
func (*PleaseDrain) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{4}
}

func (x *PleaseDrain) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PleaseDrain) GetGracePeriodSeconds() uint32 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

// SessionError terminates the session. Server-to-client only.
type SessionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionError) Reset() {
	*x = SessionError{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionError) ProtoMessage() {}

func (x *SessionError) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionError.ProtoReflect.Descriptor instead.
func (*SessionError) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{5}
}

func (x *SessionError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SessionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ControlFrame is the message format on the control stream in both
// directions after SessionAck. Ping and Pong may originate from either
// side; PleaseDrain and SessionError are server-to-client only.
type ControlFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ControlFrame_Ping
	//	*ControlFrame_PleaseDrain
	//	*ControlFrame_SessionError
	//	*ControlFrame_Pong
	Frame         isControlFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrame) Reset() {
	*x = ControlFrame{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame) ProtoMessage() {}

func (x *ControlFrame) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame.ProtoReflect.Descriptor instead.
func (*ControlFrame) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{6}
}

func (x *ControlFrame) GetFrame() isControlFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ControlFrame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Frame.(*ControlFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ControlFrame) GetPleaseDrain() *PleaseDrain {
	if x != nil {
		if x, ok := x.Frame.(*ControlFrame_PleaseDrain); ok {
			return x.PleaseDrain
		}
	}
	return nil
}

func (x *ControlFrame) GetSessionError() *SessionError {
	if x != nil {
		if x, ok := x.Frame.(*ControlFrame_SessionError); ok {
			return x.SessionError
		}
	}
	return nil
}

func (x *ControlFrame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Frame.(*ControlFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isControlFrame_Frame interface {
	isControlFrame_Frame()
}

type ControlFrame_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type ControlFrame_PleaseDrain struct {
	PleaseDrain *PleaseDrain `protobuf:"bytes,2,opt,name=please_drain,json=pleaseDrain,proto3,oneof"`
}

type ControlFrame_SessionError struct {
	SessionError *SessionError `protobuf:"bytes,3,opt,name=session_error,json=sessionError,proto3,oneof"`
}

type ControlFrame_Pong struct {
	Pong *Pong `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

func (*ControlFrame_Ping) isControlFrame_Frame() {}

func (*ControlFrame_PleaseDrain) isControlFrame_Frame() {}

func (*ControlFrame_SessionError) isControlFrame_Frame() {}

func (*ControlFrame_Pong) isControlFrame_Frame() {}

// DialReq is the first message on a dial stream (POST /dial) body. After
// this frame is read by the server, the rest of the stream is raw bytes
// bridged to the target tunnel connection.
type DialReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Host     string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port     int64                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Metadata map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// session_req is sent in /dial requests until the client has
	// received any server response, so a /dial opened in parallel with
	// /session can establish auth on its own. Once the client knows
	// /session has acked, this field is left unset.
	SessionReq    *SessionReq `protobuf:"bytes,4,opt,name=session_req,json=sessionReq,proto3" json:"session_req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialReq) Reset() {
	*x = DialReq{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialReq) ProtoMessage() {}

func (x *DialReq) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialReq.ProtoReflect.Descriptor instead.
func (*DialReq) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{7}
}

func (x *DialReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DialReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DialReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DialReq) GetSessionReq() *SessionReq {
	if x != nil {
		return x.SessionReq
	}
	return nil
}

// DialResp is the first message the server sends on a dial stream (POST
// /dial) body, after auth and endpoint resolution succeed and before the
// stream becomes raw bytes. Its presence is itself the success signal; dial
// failures are reported via DialTrailer instead.
type DialResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialResp) Reset() {
	*x = DialResp{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialResp) ProtoMessage() {}

func (x *DialResp) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialResp.ProtoReflect.Descriptor instead.
func (*DialResp) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{8}
}

func (x *DialResp) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *DialResp) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DialTrailer is sent via HTTP/2 trailers when the dial stream terminates.
type DialTrailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialTrailer) Reset() {
	*x = DialTrailer{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialTrailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialTrailer) ProtoMessage() {}

func (x *DialTrailer) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialTrailer.ProtoReflect.Descriptor instead.
func (*DialTrailer) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{9}
}

func (x *DialTrailer) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DialTrailer) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Error is returned in-band on the unary /get-* response messages.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is an ERR_NGROK_X error code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// message is the human readable message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetHostReq is the request body for /get-host.
type GetHostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostReq) Reset() {
	*x = GetHostReq{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostReq) ProtoMessage() {}

func (x *GetHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostReq.ProtoReflect.Descriptor instead.
func (*GetHostReq) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{11}
}

func (x *GetHostReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// GetHostResp is the response for /get-host. A nil error means the host exists;
// the endpoint-not-found code (ERR_NGROK_706) means it does not.
type GetHostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostResp) Reset() {
	*x = GetHostResp{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostResp) ProtoMessage() {}

func (x *GetHostResp) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostResp.ProtoReflect.Descriptor instead.
func (*GetHostResp) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{12}
}

func (x *GetHostResp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// GetHostPortReq is the request body for /get-hostport.
type GetHostPortReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int64                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostPortReq) Reset() {
	*x = GetHostPortReq{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostPortReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostPortReq) ProtoMessage() {}

func (x *GetHostPortReq) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostPortReq.ProtoReflect.Descriptor instead.
func (*GetHostPortReq) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{13}
}

func (x *GetHostPortReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetHostPortReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

// GetHostPortResp is the response for /get-hostport.
type GetHostPortResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostPortResp) Reset() {
	*x = GetHostPortResp{}
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostPortResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostPortResp) ProtoMessage() {}

func (x *GetHostPortResp) ProtoReflect() protoreflect.Message {
	mi := &file_lib_private_dial_private_dial_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostPortResp.ProtoReflect.Descriptor instead.
func (*GetHostPortResp) Descriptor() ([]byte, []int) {
	return file_lib_private_dial_private_dial_proto_rawDescGZIP(), []int{14}
}

func (x *GetHostPortResp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetHostPortResp) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *GetHostPortResp) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_lib_private_dial_private_dial_proto protoreflect.FileDescriptor

const file_lib_private_dial_private_dial_proto_rawDesc = "" +
	"\n" +
	"#lib/private_dial/private_dial.proto\x12\fprivate_dial\x1a\x1egoogle/protobuf/duration.proto\"\xb4\x01\n" +
	"\n" +
	"SessionReq\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12B\n" +
	"\bmetadata\x18\x02 \x03(\v2&.private_dial.SessionReq.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\n" +
	"SessionAck\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12>\n" +
	"\rping_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\fpingInterval\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05token\x18\x01 \x01(\x06R\x05token\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05token\x18\x01 \x01(\x06R\x05token\"W\n" +
	"\vPleaseDrain\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x120\n" +
	"\x14grace_period_seconds\x18\x02 \x01(\rR\x12gracePeriodSeconds\"<\n" +
	"\fSessionError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xee\x01\n" +
	"\fControlFrame\x12(\n" +
	"\x04ping\x18\x01 \x01(\v2\x12.private_dial.PingH\x00R\x04ping\x12>\n" +
	"\fplease_drain\x18\x02 \x01(\v2\x19.private_dial.PleaseDrainH\x00R\vpleaseDrain\x12A\n" +
	"\rsession_error\x18\x03 \x01(\v2\x1a.private_dial.SessionErrorH\x00R\fsessionError\x12(\n" +
	"\x04pong\x18\x04 \x01(\v2\x12.private_dial.PongH\x00R\x04pongB\a\n" +
	"\x05frame\"\xea\x01\n" +
	"\aDialReq\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\x12?\n" +
	"\bmetadata\x18\x03 \x03(\v2#.private_dial.DialReq.MetadataEntryR\bmetadata\x129\n" +
	"\vsession_req\x18\x04 \x01(\v2\x18.private_dial.SessionReqR\n" +
	"sessionReq\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\bDialResp\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12@\n" +
	"\bmetadata\x18\x02 \x03(\v2$.private_dial.DialResp.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\vDialTrailer\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\n" +
	"GetHostReq\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"8\n" +
	"\vGetHostResp\x12)\n" +
	"\x05error\x18\x01 \x01(\v2\x13.private_dial.ErrorR\x05error\"8\n" +
	"\x0eGetHostPortReq\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x03R\x04port\"\xe3\x01\n" +
	"\x0fGetHostPortResp\x12)\n" +
	"\x05error\x18\x01 \x01(\v2\x13.private_dial.ErrorR\x05error\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12G\n" +
	"\bmetadata\x18\x03 \x03(\v2+.private_dial.GetHostPortResp.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\"Z go.ngrok.com/lib/pb_private_dialb\x06proto3"

var (
	file_lib_private_dial_private_dial_proto_rawDescOnce sync.Once
	file_lib_private_dial_private_dial_proto_rawDescData []byte
)

func file_lib_private_dial_private_dial_proto_rawDescGZIP() []byte {
	file_lib_private_dial_private_dial_proto_rawDescOnce.Do(func() {
		file_lib_private_dial_private_dial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_private_dial_private_dial_proto_rawDesc), len(file_lib_private_dial_private_dial_proto_rawDesc)))
	})
	return file_lib_private_dial_private_dial_proto_rawDescData
}

var file_lib_private_dial_private_dial_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_lib_private_dial_private_dial_proto_goTypes = []any{
	(*SessionReq)(nil),          // 0: private_dial.SessionReq
	(*SessionAck)(nil),          // 1: private_dial.SessionAck
	(*Ping)(nil),                // 2: private_dial.Ping
	(*Pong)(nil),                // 3: private_dial.Pong
	(*PleaseDrain)(nil),         // 4: private_dial.PleaseDrain
	(*SessionError)(nil),        // 5: private_dial.SessionError
	(*ControlFrame)(nil),        // 6: private_dial.ControlFrame
	(*DialReq)(nil),             // 7: private_dial.DialReq
	(*DialResp)(nil),            // 8: private_dial.DialResp
	(*DialTrailer)(nil),         // 9: private_dial.DialTrailer
	(*Error)(nil),               // 10: private_dial.Error
	(*GetHostReq)(nil),          // 11: private_dial.GetHostReq
	(*GetHostResp)(nil),         // 12: private_dial.GetHostResp
	(*GetHostPortReq)(nil),      // 13: private_dial.GetHostPortReq
	(*GetHostPortResp)(nil),     // 14: private_dial.GetHostPortResp
	nil,                         // 15: private_dial.SessionReq.MetadataEntry
	nil,                         // 16: private_dial.DialReq.MetadataEntry
	nil,                         // 17: private_dial.DialResp.MetadataEntry
	nil,                         // 18: private_dial.GetHostPortResp.MetadataEntry
	(*durationpb.Duration)(nil), // 19: google.protobuf.Duration
}
var file_lib_private_dial_private_dial_proto_depIdxs = []int32{
	15, // 0: private_dial.SessionReq.metadata:type_name -> private_dial.SessionReq.MetadataEntry
	19, // 1: private_dial.SessionAck.ping_interval:type_name -> google.protobuf.Duration
	2,  // 2: private_dial.ControlFrame.ping:type_name -> private_dial.Ping
	4,  // 3: private_dial.ControlFrame.please_drain:type_name -> private_dial.PleaseDrain
	5,  // 4: private_dial.ControlFrame.session_error:type_name -> private_dial.SessionError
	3,  // 5: private_dial.ControlFrame.pong:type_name -> private_dial.Pong
	16, // 6: private_dial.DialReq.metadata:type_name -> private_dial.DialReq.MetadataEntry
	0,  // 7: private_dial.DialReq.session_req:type_name -> private_dial.SessionReq
	17, // 8: private_dial.DialResp.metadata:type_name -> private_dial.DialResp.MetadataEntry
	10, // 9: private_dial.GetHostResp.error:type_name -> private_dial.Error
	10, // 10: private_dial.GetHostPortResp.error:type_name -> private_dial.Error
	18, // 11: private_dial.GetHostPortResp.metadata:type_name -> private_dial.GetHostPortResp.MetadataEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_lib_private_dial_private_dial_proto_init() }
func file_lib_private_dial_private_dial_proto_init() {
	if File_lib_private_dial_private_dial_proto != nil {
		return
	}
	file_lib_private_dial_private_dial_proto_msgTypes[6].OneofWrappers = []any{
		(*ControlFrame_Ping)(nil),
		(*ControlFrame_PleaseDrain)(nil),
		(*ControlFrame_SessionError)(nil),
		(*ControlFrame_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_private_dial_private_dial_proto_rawDesc), len(file_lib_private_dial_private_dial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_private_dial_private_dial_proto_goTypes,
		DependencyIndexes: file_lib_private_dial_private_dial_proto_depIdxs,
		MessageInfos:      file_lib_private_dial_private_dial_proto_msgTypes,
	}.Build()
	File_lib_private_dial_private_dial_proto = out.File
	file_lib_private_dial_private_dial_proto_goTypes = nil
	file_lib_private_dial_private_dial_proto_depIdxs = nil
}
