name: Go
on:
  push:
    branches: [ "main", "privatedial" ]
  pull_request:
    branches: [ "main", "privatedial" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NGROK_TEST_FLAKEY: 1
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
    - uses: HatsuneMiku3939/direnv-action@fe6ca688de409566c44001c1e65ad6925f0e9cbb # v1
    - name: direnv allow
      run: direnv allow .
    - name: go mod tidy
      run: direnv exec . go mod tidy
    - name: exit if not tidy
      run: |
        git diff --exit-code go.mod
        git diff --exit-code go.sum
    - name: Build
      run: direnv exec . go build -v ./...
    - name: Build Examples
      run: direnv exec . go build -C ./examples -v ./...
    - name: Test
      run: direnv exec . go test -v ./...
  online-tests:
    name: Online tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork
    env:
      NGROK_TEST_ONLINE: 1
      NGROK_TEST_FLAKEY: 1
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
    - uses: HatsuneMiku3939/direnv-action@fe6ca688de409566c44001c1e65ad6925f0e9cbb # v1
    - name: direnv allow
      run: direnv allow .
    - name: Test
      run: direnv exec . go test -mod=readonly -v ./...
